# Generated by Django 2.1.4 on 2019-11-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='expires_at',
        ),
    ]
